<<<<<<< HEAD
import ShoppingCart from "@/components/templates/ShoppingCart";
import Head from "next/head";

=======

import BBApp from "@/components/BBApp";
import Head from "next/head";


>>>>>>> 0db11984dc0755bf1c0e14ba3af9a17d810b4c24
export default function Home() {
  return (
    <>
      <Head>
<<<<<<< HEAD
        <title>Shopping Cart</title>
=======
        <title>Breaking Bad</title>
>>>>>>> 0db11984dc0755bf1c0e14ba3af9a17d810b4c24
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>
<<<<<<< HEAD
      
      <ShoppingCart/>

    
=======

      <BBApp/>
>>>>>>> 0db11984dc0755bf1c0e14ba3af9a17d810b4c24
    </>
  );
}
